//package exceptions;
//
//class ArithmeticTest {
//	public static void division(int num1, int num2) {
//		int result = 0;
//		try {
//			result = num1 / num2;
//		} catch(ArithmeticException ex) {
//			System.out.println("Exception Occurred.");
//			System.out.println("Exception: " + ex.getMessage());
//		} finally {
//			System.out.println("Division: " + result);
//		}
//		System.out.println("Remaining Code Here..");
//	}
//}
//
//public class ExceptionHandlingExampleThree {
//
//	public static void main(String[] args) {
//		ArithmeticTest.division(100, 0); 		// Exception
//	}
//	
//}
