//package exceptions;
//
//class ArithmeticTest {
//	public static void division(int num1, int num2) {
//		try {
//			int result = num1 / num2;
//			System.out.println("Division: " + result);
//		} catch(Exception ex) {
//			System.out.println("Exception Occurred.");
//			System.out.println("Exception: " + ex.getMessage());
//		}
//	}
//}
//
//public class ExceptionHandlingExampleTwo {
//
//	public static void main(String[] args) {
//		ArithmeticTest.division(100, 20);	// 5
//		ArithmeticTest.division(0, 20); 		// 0
//		ArithmeticTest.division(100, 0); 		// 
//	}
//	
//}
